name: hatch_dummy
on:
  push:
    tags:
        - 'v*.*.*'
  workflow_dispatch:
    
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}
      - name: Set output
        id: vars
        run: echo "tag=${GITHUB_REF#refs/*/}" >> $GITHUB_OUTPUT
      - name: Check output
        env:
          RELEASE_VERSION: ${{ steps.vars.outputs.tag }}
        run: |
          echo $RELEASE_VERSION
          echo ${{ steps.vars.outputs.tag }}
      - name: Install dependencies
        run: |
          python -m pip install hatch
      - name: Build and publish
        env:
          HATCH_INDEX_REPO: "https://test.pypi.org/legacy/"
          HATCH_INDEX_USER: __token__
          HATCH_INDEX_AUTH: ${{ secrets.PYPI_TEST_TOKEN }}
        run: |
          hatch version "{RELEASE_VERSION}"
          hatch build
          hatch publish
          
