name: Publish to PyPI
on:
  release:
    types: [published]
  workflow_dispatch:
    
jobs:
  deploy:
    runs-on: ubuntu-latest
    if: contains(github.ref, 'tags')
    steps:
      - uses: actions/checkout@v3
      - name: Set up Python
        uses: actions/setup-python@v4
      - run: python3 -m pip install --upgrade build && python3 -m build
      - name: Publish package distributions to PyPI
        uses: pypa/gh-action-pypi-publish@release/v1
        with:
          password: ${{ secrets.PYPI_TEST_TOKEN }}
          repository-url: https://test.pypi.org/legacy/
